before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
before_script:
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
cache:
  directories:
  - $HOME/.m2
dist: trusty
jdk:
- oraclejdk8
language: java
matrix:
  include:
  - install: true
    script: echo "MAVEN_OPTS='-Xmx3000m'" > ~/.mavenrc && mvn clean -Pstrict -pl '!benchmarks'
      compile test-compile -B
    sudo: false
  - before_script:
    - unset _JAVA_OPTIONS
    install: echo "MAVEN_OPTS='-Xmx3000m'" > ~/.mavenrc && mvn install -q -ff -DskipTests
      -B
    script: echo "MAVEN_OPTS='-Xmx512m'" > ~/.mavenrc && mvn test -B -Pparallel-test
      -Dmaven.fork.count=2 -pl processing
    sudo: false
  - before_script:
    - unset _JAVA_OPTIONS
    install: echo "MAVEN_OPTS='-Xmx3000m'" > ~/.mavenrc && mvn install -q -ff -DskipTests
      -B
    script: echo "MAVEN_OPTS='-Xmx512m'" > ~/.mavenrc && mvn test -B -Pparallel-test
      -Dmaven.fork.count=2 -pl '!processing'
    sudo: false
  - after_failure:
    - for v in ~/shared/logs/*.log ; do echo $v logtail ======================== ;
      tail -100 $v ; done
    - for v in broker middlemanager overlord router coordinator historical ; do echo
      $v dmesg ======================== ; docker exec -it druid-$v sh -c 'dmesg |
      tail -3' ; done
    env:
    - DOCKER_IP=172.17.0.1
    install:
    - mvn install -q -ff -DskipTests -B
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_integration.sh
    services:
    - docker
    sudo: required
script:
- touch NOW
- echo GIBSTUDYSTART $(date)
- mvn test -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then echo TESTNUM $(find . -name TEST-*.xml
  -newer NOW | wc -l);        else echo TESTNUM $(find -name TEST-*.xml -newer NOW
  | wc -l);        fi
